docker-backup:
  build: .
  volumes:
    - ./certs:/certs
    - ./data:/data
  cap_add:
    - SYS_ADMIN
  devices:
    - "/dev/fuse"
  environment:
    GPG_PUBLIC_KEY: {path_to_backup_public_key}
    WEBDAV_HOST: {webdav_url}
    WEBDAV_USER: {webdav_user}
    WEBDAV_PASSWORD: {webdav_password}
    SMTP_HUB: {smtp_hub}
    SMTP_USER: {smtp_user}
    SMTP_PASS: {smtp_pass}
    SMTP_DOMAIN: {smtp_domain}
    SMTP_HOSTNAME: {smtp_hostname}
    BACKUP_DIRS: {filepath_to_archive_seperated_by_space}
