#!/bin/sh
echo $WEBDAV_HOST $WEBDAV_USER $WEBDAV_PASSWORD > /etc/davfs2/secrets
echo $WEBDAV_HOST" /mnt/backup davfs user,rw,auto 0 0" > /etc/fstab

mount /mnt/backup

NOW=$(date +%Y/%m/%d/%H_%M)

mkdir -p /mnt/backup/$NOW
cd /mnt/backup/$NOW


echo "blaat"

#umount /mnt/backup

#kill 1
