#!/bin/bash
echo $WEBDAV_HOST $WEBDAV_USER $WEBDAV_PASSWORD > /etc/davfs2/secrets
echo $WEBDAV_HOST" /mnt/backup davfs user,rw,auto 0 0" > /etc/fstab

mount /mnt/backup

NOW=$(date +%Y/%m/%d/%H_%M)

mkdir -p /tmp/backup
mkdir -p /mnt/backup/$NOW
cd /mnt/backup/$NOW

echo 'Backup Directories'
arrDIRS=($BACKUP_DIRS)
for i in "${arrDIRS[@]}"
do
   arrDETAILS=(${i//:/ })
   DIR=${arrDETAILS[0]}
   ARCHIVENAME=${arrDETAILS[1]}.tar.gz.gpg
   echo Create backup $DIR to $ARCHIVENAME
   tar -zc $DIR | gpg --trust-model always -e -r backup -o /tmp/backup/$ARCHIVENAME
done

echo 'Backup Mysql Database'
arrMYSQL=($BACKUP_MYSQL)
for i in "${BACKUP_MYSQL[@]}"
do
   arrDETAILS=(${i//:/ })
   HOST=${arrDETAILS[0]}
   DB=${arrDETAILS[1]}
   USER=${arrDETAILS[2]}
   PASS=${arrDETAILS[3]}
   ARCHIVENAME=${arrDETAILS[4]}.sql.gz.gpg
   echo Create backup of database $HOST:$DB to $ARCHIVENAME
   mysqldump -h $HOST -u $USER -p$PASS $DB | gzip -9 | gpg --trust-model always -e -r backup -o /tmp/backup/$ARCHIVENAME
done

cp -R /tmp/backup/* /mnt/backup/$NOW/

echo 'backup is syncing to server...'
sleep 20
umount -l /mnt/backup
rm -rf /tmp/backup

kill 1
